import client from './client';
import { unwrapListPayload } from './helpers.js';
export const internshipService = {
  fetchPlacements:(p)=>client.get('/placements/',{params:p}).then(r=>unwrapListPayload(r.data)),
  createPlacement:(d)=>client.post('/placements/',d).then(r=>r.data),
  updatePlacement:(id,d)=>client.patch(`/placements/${id}/`,d).then(r=>r.data),
  deletePlacement:(id)=>client.delete(`/placements/${id}/`).then(r=>r.data),
  fetchActivities:(p)=>client.get('/activities/',{params:p}).then(r=>unwrapListPayload(r.data)),
  createActivity:(d)=>client.post('/activities/',d).then(r=>r.data),
  updateActivity:(id,d)=>client.patch(`/activities/${id}/`,d).then(r=>r.data),
  deleteActivity:(id)=>client.delete(`/activities/${id}/`).then(r=>r.data),
  approveActivity:(id,note)=>client.post(`/activities/${id}/approve/`,{note}).then(r=>r.data),
  returnActivity:(id,note)=>client.post(`/activities/${id}/return/`,{note}).then(r=>r.data),
  validateActivity:(id,note)=>client.post(`/activities/${id}/validate/`,{note}).then(r=>r.data),
  rejectActivity:(id,note)=>client.post(`/activities/${id}/reject/`,{note}).then(r=>r.data),
  clockIn:(coords)=>client.post('/attendance/clock-in/',coords).then(r=>r.data),
  clockOut:()=>client.post('/attendance/clock-out/',{}).then(r=>r.data),
  fetchAttendance:(p)=>client.get('/attendance/',{params:p}).then(r=>unwrapListPayload(r.data)),
  fetchEvaluations:(p)=>client.get('/evaluations/',{params:p}).then(r=>unwrapListPayload(r.data)),
  submitEvaluation:(d)=>client.post('/evaluations/',d).then(r=>r.data),
  updateEvaluation:(id,d)=>client.patch(`/evaluations/${id}/`,d).then(r=>r.data),
  fetchPeriods:()=>client.get('/periods/').then(r=>unwrapListPayload(r.data)),
  createPeriod:(d)=>client.post('/periods/',d).then(r=>r.data),
  updatePeriod:(id,d)=>client.patch(`/periods/${id}/`,d).then(r=>r.data),
  deletePeriod:(id)=>client.delete(`/periods/${id}/`).then(r=>r.data),
  fetchCompanies:()=>client.get('/companies/').then(r=>unwrapListPayload(r.data)),
  createCompany:(d)=>client.post('/companies/',d).then(r=>r.data),
  updateCompany:(id,d)=>client.patch(`/companies/${id}/`,d).then(r=>r.data),
  deleteCompany:(id)=>client.delete(`/companies/${id}/`).then(r=>r.data),
  generateReport:(type,p)=>client.get(`/reports/${type}/`,{params:p,responseType:'blob'}).then(r=>r.data),
};
