# Generated by Django 5.2.13 on 2026-04-26 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'mentor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.PROTECT, related_name='issued_evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='internships.internshipperiod'),
        ),
        migrations.AddField(
            model_name='placement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='internships.company'),
        ),
        migrations.AddField(
            model_name='placement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placement',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'role': 'lecturer'}, on_delete=django.db.models.deletion.PROTECT, related_name='lecturer_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placement',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.PROTECT, related_name='mentor_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placement',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='internships.internshipperiod'),
        ),
        migrations.AddField(
            model_name='placement',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='internships.placement'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('student', 'period')},
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['company', 'period'], name='internships_company_4cd3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['lecturer', 'mentor'], name='internships_lecture_1a29a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='placement',
            unique_together={('student', 'period')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['student', 'status'], name='internships_student_b77879_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['mentor', 'status'], name='internships_mentor__78e3ad_idx'),
        ),
    ]
